// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package mod

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB757a988DecodeGithubComVitorsalgadoRinhaBackend2024Q1GoInternalMod(in *jlexer.Lexer, out *Transacao) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "descricao":
			out.Descricao = string(in.String())
		case "tipo":
			out.Tipo = string(in.String())
		case "valor":
			out.Valor = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB757a988EncodeGithubComVitorsalgadoRinhaBackend2024Q1GoInternalMod(out *jwriter.Writer, in Transacao) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"descricao\":"
		out.RawString(prefix[1:])
		out.String(string(in.Descricao))
	}
	{
		const prefix string = ",\"tipo\":"
		out.RawString(prefix)
		out.String(string(in.Tipo))
	}
	{
		const prefix string = ",\"valor\":"
		out.RawString(prefix)
		out.Int(int(in.Valor))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Transacao) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB757a988EncodeGithubComVitorsalgadoRinhaBackend2024Q1GoInternalMod(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Transacao) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB757a988EncodeGithubComVitorsalgadoRinhaBackend2024Q1GoInternalMod(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Transacao) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB757a988DecodeGithubComVitorsalgadoRinhaBackend2024Q1GoInternalMod(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Transacao) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB757a988DecodeGithubComVitorsalgadoRinhaBackend2024Q1GoInternalMod(l, v)
}
func easyjsonB757a988DecodeGithubComVitorsalgadoRinhaBackend2024Q1GoInternalMod1(in *jlexer.Lexer, out *Resumo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "limite":
			out.Limite = int(in.Int())
		case "saldo":
			out.Saldo = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB757a988EncodeGithubComVitorsalgadoRinhaBackend2024Q1GoInternalMod1(out *jwriter.Writer, in Resumo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"limite\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Limite))
	}
	{
		const prefix string = ",\"saldo\":"
		out.RawString(prefix)
		out.Int(int(in.Saldo))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Resumo) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB757a988EncodeGithubComVitorsalgadoRinhaBackend2024Q1GoInternalMod1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Resumo) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB757a988EncodeGithubComVitorsalgadoRinhaBackend2024Q1GoInternalMod1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Resumo) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB757a988DecodeGithubComVitorsalgadoRinhaBackend2024Q1GoInternalMod1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Resumo) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB757a988DecodeGithubComVitorsalgadoRinhaBackend2024Q1GoInternalMod1(l, v)
}
