version: "3.5"

services:
  api01: &api
    build:
      context: ./
    container_name: api01
    hostname: api01
    environment:
      - DB_CONN_STRING=user=admin password=123 dbname=rinha host=/var/run/postgresql sslmode=disable pool_min_conns=50 pool_max_conns=210
      #- GOMAXPROCS=1
      #- GOMEMLIMIT=21MiB
      #- GOGC=off
    volumes:
      - pgsql_socket:/var/run/postgresql
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "25MB"

  api02:
    <<: *api
    hostname: api02
    container_name: api02
 
  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    command: postgres -c max_connections=450 -c checkpoint_timeout=600 -c synchronous_commit=0 -c fsync=0 -c full_page_writes=0
    volumes:
      - ./conf/script.sql:/docker-entrypoint-initdb.d/script.sql
      - pgsql_socket:/var/run/postgresql
    deploy:
      resources:
        limits:
          cpus: "0.9"
          memory: "450MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1

volumes:
  pgsql_socket:
