version: "3.5"

services:
  api01: &api
    build:
      context: ./
    container_name: api01
    hostname: api01
    network_mode: host
    environment:
      - DB_CONN_STRING=user=rinha password=rinha dbname=rinha host=0.0.0.0 port=6432 sslmode=disable pool_min_conns=5 pool_max_conns=5
      - ADDR=:8081
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  api02:
    <<: *api
    container_name: api02
    hostname: api02
    network_mode: host
    environment:
      - DB_CONN_STRING=user=rinha password=rinha dbname=rinha host=0.0.0.0 port=6432 sslmode=disable pool_min_conns=5 pool_max_conns=5
      - ADDR=:8082

  envoy:
    image: envoyproxy/envoy:v1.29-latest
    container_name: envoy
    network_mode: host
    expose:
      - "9999"
    volumes:
      - ./conf/envoy.yaml:/etc/envoy/envoy.yaml:ro
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml --concurrency 1
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"

  db:
    image: postgres:16.2
    container_name: db
    environment:
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha
    network_mode: host
    expose:
      - "5432"
    volumes:
      - ./conf/script.sql:/docker-entrypoint-initdb.d/script.sql
    command: postgres -c max_connections=300 -c checkpoint_timeout=600 -c synchronous_commit=off -c fsync=off -c full_page_writes=off -c work_mem=16MB -c shared_buffers=75MB -c maintenance_work_mem=25MB -c effective_cache_size=75MB -c max_worker_processes=1 -c max_parallel_workers=1 -c max_parallel_maintenance_workers=1 -c max_parallel_workers_per_gather=1
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "330MB"

  bouncer:
    build:
      context: .
      dockerfile: Dockerfile.bouncer
    container_name: bouncer
    environment:
      PGB_DATABASES: rinha = host=0.0.0.0 port=5432 pool_mode=statement pool_size=20
      PGB_ADMIN_USERS: rinha
      PGB_ADMIN_PASSWORDS: rinha
    network_mode: host
    expose:
      - "6432"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"
