version: "3.5"

services:
  api01: &api
    build:
      context: ./
    container_name: api01
    hostname: api01
    environment:
      - DB_CONN_STRING=user=admin password=123 dbname=rinha host=/var/run/postgresql sslmode=disable pool_min_conns=10 pool_max_conns=50
    volumes:
      - pgsql_socket:/var/run/postgresql
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  api02:
    <<: *api
    hostname: api02
    container_name: api02

  envoy:
    image: envoyproxy/envoy:v1.29-latest
    container_name: envoy
    ports:
      - "9999:9999"
    volumes:
      - ./conf/envoy.yaml:/etc/envoy/envoy.yaml:ro
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "200MB"

  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    command: postgres -c max_connections=300 -c work_mem=16MB -c checkpoint_timeout=600 -c synchronous_commit=off -c fsync=off -c full_page_writes=off
    volumes:
      - ./conf/script.sql:/docker-entrypoint-initdb.d/script.sql
      - pgsql_socket:/var/run/postgresql
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "250MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1

volumes:
  pgsql_socket:
