version: "3.5"

services:
  api01: &api
    build:
      context: ./
    container_name: api01
    hostname: api01
    environment:
      - DB_CONN_STRING=user=rinha password=rinha dbname=rinha host=bouncer port=6432 sslmode=disable pool_min_conns=5 pool_max_conns=5
      - GOMAXPROCS=2
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "75MB"

  api02:
    <<: *api
    hostname: api02
    container_name: api02

  envoy:
    image: envoyproxy/envoy:v1.29-latest
    container_name: envoy
    ports:
      - "9999:9999"
    volumes:
      - ./conf/envoy.yaml:/etc/envoy/envoy.yaml:ro
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "180MB"

  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./conf/script.sql:/docker-entrypoint-initdb.d/script.sql
      - ./conf/postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "200MB"

  bouncer:
    build:
      context: .
      dockerfile: Dockerfile.bouncer
    container_name: bouncer
    environment:
      PGB_DATABASES: rinha = host=db port=5432 pool_mode=statement pool_size=20
      PGB_ADMIN_USERS: rinha
      PGB_ADMIN_PASSWORDS: rinha
    ports:
      - "6432:6432"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"
    depends_on:
      - db

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
