name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  GATLING_VERSION: 3.10.3
  RINHA_DIR: rinha-de-backend-2024-q1

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.22

      - name: checkout
        uses: actions/checkout@v4

      - name: deps
        run: make deps

      - name: build
        run: make build

      - name: test
        run: make test

  load-test:
    name: load-test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: running everything
        run: docker-compose up --build --force-recreate -d

      - name: test
        run: |
          git clone --depth 1 --single-branch -b main https://github.com/zanfranceschi/rinha-de-backend-2024-q1.git
          wget -P $RINHA_DIR https://repo1.maven.org/maven2/io/gatling/highcharts/gatling-charts-highcharts-bundle/$GATLING_VERSION/gatling-charts-highcharts-bundle-$GATLING_VERSION-bundle.zip
          unzip -d $RINHA_DIR $RINHA_DIR/gatling-charts-highcharts-bundle-$GATLING_VERSION-bundle.zip
          ./bin/executar-teste-local

          echo GATLING_REPORT=$(ls $RINHA_DIR/load-test/user-files/results | sort | head -n 1) >> $GITHUB_ENV
          
      - name: upload test results
        uses: actions/upload-pages-artifact@v3
        with: 
          path: $RINHA_DIR/load-test/user-files/results/${{ env.GATLING_REPORT }}
