name: publish docker image

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build docker image and push
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN
          docker build -t vitorsalgado/rinha-2024-q1 .
          docker push vitorsalgado/rinha-2024-q1
